define(function() {
  return {
    creditCard: {
      itau: ""
+ "JOAO SILVA SANTOS Agência: 1234Conta: 12345-9Acessar outras contasEncerrar sessão\n"
+ "Itaú Personnalite\n"
+ "Home|Conta Corrente|Poupança|Investimentos|Pagamentos|Crédito|Cartões|Seguros|Transferência, DOC e TED|Previdência|Conveniência|Experiência|Mais Produtos|Personnalité Digital \n"
+ "\n"
+ "Home > Cartões > Minha fatura > Ver fatura e limites\n"
+ "\n"
+ "Consulta à fatura\n"
+ " Fatura anterior		 Próxima fatura\n"
+ "Meu cartão: 	PERSONNALITE MASTERCARD PLATINUM - final 1234\n"
+ " 	Cartão de crédito	\n"
+ "Resumo da fatura em R$\n"
+ "Total da fatura anterior	20.011,51\n"
+ "Créditos e Pagamentos	20.110,09\n"
+ "Débitos e despesas nacionais	1.267,63\n"
+ "Total desta fatura	13.952,54\n"
+ " \n"
+ " \n"
+ " 	Titular: 	JOAO SILVA SANTOS\n"
+ " 	Cartão: 	5148.XXXX.XXXX.1234\n"
+ " \n"
+ "vencimento03/01/2016pagamento\n"
+ "total13.952,54R$pagamento\n"
+ "mínimo2.092,87R$parcelamento\n"
+ "da faturaR$Não disponível\n"
+ " \n"
+ " 	\n"
+ "Limites de crédito R$\n"
+ "Limite total\n"
+ "de crédito	43.000,00\n"
+ "De retirada de recursos\n"
+ "País (saque)	1.000,00\n"
+ "De retirada de recursos\n"
+ "Exterior (saque)	7.000,00\n"
+ "\n"
+ "Encargos desta fatura entre\n"
+ "03/12/16 e 02/01/16\n"
+ "Juros de	10,10%\n"
+ "financiamento	R$ 0,00\n"
+ "Juros de	1,00% a.m.\n"
+ "Mora	R$ 0,00\n"
+ "Multa por	2,00%\n"
+ "atraso	R$ 0,00\n"
+ "IOF de\n"
+ "financiamento	R$ 0,00\n"
+ "\n"
+ "Fique atento aos encargos para o próximo período (04/01/16 a 03/02/16)\n"
+ "Juros máximos	14,23% a.m.\n"
+ "do contrato	404,65% a.a.\n"
+ "\n"
+ "\n"
+ "Financiamento da Fatura\n"
+ "Valor da fatura\n"
+ "atual	R$ 13.952,54\n"
+ "Juros de	14,23% a.m.\n"
+ "financiamento	404,65% a.a.\n"
+ "Encargos em caso\n"
+ "de pgto. mínimo (R$)	1.687,63\n"
+ "CET do financiamento	14,85% a.m.\n"
+ "da fatura	439,34% a.a.\n"
+ "Valor total	R$ 11.859,67\n"
+ "financiado	(100,00%)\n"
+ "Valor do IOF	R$ 74,24\n"
+ "Valor total a\n"
+ "pagar	R$ 13.621,54\n"
+ "\n"
+ "\n"
+ "Compras parceladas com juros\n"
+ "Limite de crédito	R$ 43.000,00\n"
+ "Juros da compra	2,99% a.m.\n"
+ "parcelada	43,11% a.a.\n"
+ "CET da compra	3,25% a.m.\n"
+ "parcelada	47,56% a.a.\n"
+ "Valor total	R$ 43.000,00\n"
+ "financiado	(100,00%)\n"
+ "Valor do IOF	R$ 1.222,65\n"
+ "Valor total a\n"
+ "pagar	R$ 60.871,44\n"
+ "\n"
+ "Demais Taxas de Juros\n"
+ "De retirada de	 \n"
+ "recursos país	15,13% a.m.\n"
+ "De pagamento	 \n"
+ "de contas	2,99% a.m.\n"
+ " 	\n"
+ "Movimentações\n"
+ "DATA	MOVIMENTAÇÃO	VALOR EM R$\n"
+ "23/11	PAGAMENTO EFETUADO	-20.011,51\n"
+ "17/12	CR DIFERENCA COTACAO U$	-98,58\n"
+ "Total de créditos efetuados	-20.110,09\n"
+ "Total de débitos efetuados	0,00\n"
+ "\n"
+ "Lançamentos nacionais\n"
+ "JOAO SILVA SANTOS (5020)\n"
+ "DATA	MOVIMENTAÇÃO	VALOR EM R$\n"
+ "23/09	PORTO SEGURO SEGUR03/06	746,27\n"
+ "Crédito do cartão final (5020)	0,00\n"
+ "Débito do cartão final (5020)	746,27\n"
+ "\n"
+ "Lançamentos nacionais\n"
+ "JOAO SILVA SANTOS (1234)\n"
+ "DATA	MOVIMENTAÇÃO	VALOR EM R$\n"
+ "28/11	PAO DE ACUCAR-2337-DEL	521,36\n"
+ "Crédito do cartão final (1234)	0,00\n"
+ "Débito do cartão final (1234)	521,36\n"
+ "\n"
+ "Lançamentos internacionais\n"
+ "JOAO SILVA SANTOS (5020)\n"
+ "DATA	MOVIMENTAÇÃO	VALOR EM R$\n"
+ "21/11	TARGET 00000133	232,84\n"
+ " 	UNITED STATES	58,54 (U.S.DOLLAR)\n"
+ "21/11	GENGHIS GRILL DALLAS G	58,22\n"
+ " 	UNITED STATES	14,34 (U.S.DOLLAR)\n"
+ "21/11	GODIVA 134	259,31\n"
+ " 	UNITED STATES	63,87 (U.S.DOLLAR)\n"
+ "21/11	BAG N BAGGAGE 23 GALLE	54,93\n"
+ " 	UNITED STATES	13,53 (U.S.DOLLAR)\n"
+ "22/11	LE MERIDIEN DALLAS GAL	10.355,84\n"
+ " 	UNITED STATES	2.550,70 (U.S.DOLLAR)\n"
+ "23/11	IOF COMPRA INTERNACIONA	15,16\n"
+ " 	 	3,73 (U. S. DOLLAR)\n"
+ "23/11	IOF COMPRA INTERNACIONA	3,70\n"
+ " 	 	0,91 (U. S. DOLLAR)\n"
+ "24/11	IOF COMPRA INTERNACIONA	16,52\n"
+ " 	 	4,07 (U. S. DOLLAR)\n"
+ "24/11	IOF COMPRA INTERNACIONA	3,49\n"
+ " 	 	0,86 (U. S. DOLLAR)\n"
+ "24/11	IOF COMPRA INTERNACIONA	660,69\n"
+ " 	 	162,73 (U. S. DOLLAR)\n"
+ "24/11	NATIONAL CAR TOLLS	150,55\n"
+ " 	UNITED STATES	37,08 (U.S.DOLLAR)\n"
+ "26/11	IOF COMPRA INTERNACIONA	9,62\n"
+ " 	 	2,37 (U. S. DOLLAR)\n"
+ "Crédito cartão final (5020) em R$	0,00\n"
+ "Total retiradas exterior em R$	0,00\n"
+ "Total transações inter. em R$	11.111,69\n"
+ "Repasse de IOF em R$	709,18\n"
+ "Total dos lançamentos inter. em R$	11.820,87\n"
+ "Dólar de conversão	4,06\n"
+ "\n"
+ "Lançamentos internacionais\n"
+ "JOAO SILVA SANTOS (1234)\n"
+ "DATA	MOVIMENTAÇÃO	VALOR EM R$\n"
+ "04/12	VENETIAN/PALAZZO ROOM	904,89\n"
+ " 	UNITED STATES	222,88 (U.S.DOLLAR)\n"
+ "07/12	IOF COMPRA INTERNACIONA	57,73\n"
+ " 	 	14,22 (U. S. DOLLAR)\n"
+ "Crédito cartão final (1234) em R$	0,00\n"
+ "Total retiradas exterior em R$	0,00\n"
+ "Total transações inter. em R$	904,89\n"
+ "Repasse de IOF em R$	57,73\n"
+ "Total dos lançamentos inter. em R$	962,62\n"
+ "Dólar de conversão	4,06\n"
+ "\n"
+ " \n"
+ " \n"
+ "(1) Se a cotação do Dólar acima for diferente da cotação na data do vencimento, os ajustes (crédito ou débito) serão feitos na próxima fatura, sem encargos. Caso esta fatura seja paga antes do vencimento, a diferença de cotação será calculada com base no valor do Dólar do dia do pagamento.\n"
+ "- Em decorrência da regulamentação do Banco Central do Brasil, circular 3.512 de 25 de novembro de 2010, o valor mínimo da fatura de cartão de crédito a ser pago mensalmente não poderá ser inferior aos seguintes valores: 15% do valor total da fatura - a partir de junho de 2011; e 20% do valor total da fatura - a partir de 1º de dezembro de 2011.\n"
+ "O valor do pagamento mínimo do seu cartão será calculado de acordo com tais percentuais, a partir das datas acima.\n"
+ "Atenção\n"
+ "- Para garantir ainda mais segurança e tranqüilidade em suas compras, o Cartão Personnalité MasterCard possui um sistema de monitoramento eletrônico que identifica possíveis desvios no perfil de utilização do seu cartão. Caso necessário, será solicitado que você confirme alguns dados ligando para a Central do Cartão Personnalité. Este procedimento é importante para garantir que seu Cartão Personnalité MasterCard seja utilizado somente por você.\n"
+ "Aviso\n"
+ "- A planilha CET está disponível na Central de Atendimento do seu cartão de crédito.\n"
+ "- Para sua conveniência e conforme contrato, se não ocorrer o pagamento desta fatura até o 10º dia após o vencimento, o valor do pagamento mínimo poderá ser debitado em sua conta corrente que possuir saldo disponível suficiente. Para inibir o débito deste mês, procure a Agência Itaú mais próxima até o 8º dia após o vencimento.\n"
+ " \n"
+ "Opções\n"
+ " Imprimir Fatura  \n"
+ " Boleto para pagamento\n"
+ "Ir para\n"
+ "Histórico de faturas\n"
+ "Demonstrativo gráfico da fatura\n"
+ "Comparativo gráfico por período\n"
+ "Pagamento desta fatura\n"
+ "Consultas a compras parceladas\n"
+ "Parcelamento desta fatura\n"
+ "Consultar número do cartão\n"
+ "Atendimento online Cartão Personnalité\n"
+ "Ir para a Cadastrar Fatura Digital\n"
+ "Fale com o Itaú Personnalité\n"
+ "\n"
+ "Itaú Unibanco S.A.     |     Atendimento     |     Segurança     |     Mapa do site     |      Acompanhe: Acompanhe o Personnalité no Facebook  Acompanhe o Itaú no Twitter  Acompanhe o Itaú via RSS  Acompanhe o Itaú no Youtube\n"
      ,
      nubank: ""
    }
  }
});